dbt_learn:
  outputs:
    dev:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: airbnb
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: TRANSFORM
      schema: dev
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: COMPUTE_WH
  target: dev
