-- Use an admin role
USE ROLE ACCOUNTADMIN;

-- Create the `transform` role and grant it to admin role
CREATE ROLE IF NOT EXISTS transform;
GRANT ROLE transform TO ROLE ACCOUNTADMIN;

-- Create the default warehouse if necessary
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH;
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;

-- Create the `dbt` user and assign to role
CREATE USER IF NOT EXISTS dbt
PASSWORD = 'dbtPassword123'
LOGIN_NAME = 'dbt'
MUST_CHANGE_PASSWORD=FALSE
DEFAULT_ROLE= 'transform'
DEFAULT_WAREHOUSE = 'COMPUTE_WH'
DEFAULT_NAMESPACE = 'AIRBNB.RAW'
COMMENT = 'dbt user for data transformation';

GRANT ROLE TRANSFORM TO USER dbt;


-- Create database and schemas
CREATE DATABASE IF NOT EXISTS AIRBNB;
CREATE SCHEMA IF NOT EXISTS AIRBNB.RAW;

-- Set up permissions to role `transform`
GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE transform; 
GRANT ALL ON DATABASE AIRBNB to ROLE transform;
GRANT ALL ON ALL SCHEMAS IN DATABASE AIRBNB to ROLE transform;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE AIRBNB to ROLE transform;
GRANT ALL ON ALL TABLES IN SCHEMA AIRBNB.RAW to ROLE transform;
GRANT ALL ON FUTURE TABLES IN SCHEMA AIRBNB.RAW to ROLE transform;